### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by 0b11001111** [wahlbilanz/DeinWal.de#82]
Die Website ist gerade nicht erreibar: 502 Bad Gateway.

**Comment by binfalse** [comment]
whaa, mist in der nginx config gemacht :/

ist gehotfixt, pipeline baut gerade...

danke fuers schnelle bescheid sagen!! sollte mal monitoring dafuer anschalten... :)

**Comment by 0b11001111** [comment]
Das ging flott!

Sehr geiles Projekt übrigens, danke für eure Arbeit!
