### ISSUE TITLE
Darstellung Abstimmungsergebnis anpassen

### ISSUE THREAD

**Issue by d-nnis** [wahlbilanz/DeinWal.de#9]
Hallo Deinwal-Team!

Danke für die Website und die Möglichkeit, die Wah(l/r)heit nachzuvollziehen!

Für die nachvollziehbarere Darstellung der Ergebnisse empfehle ich, die Berechnung der Prozente in der richtigen Reihenfolge anzuzeigen. D.h. die Faktoren der Score in der Reihenfolge, wie die Zeile drüber aufstellen (Bsp. s.a. Screenshot).

![deinwahl](https://user-images.githubusercontent.com/1454499/29467290-32f74f4c-8440-11e7-9839-d442f12c3ae0.png)

**Comment by binfalse** [comment]
Du meinst statt

    (Enthaltung + 1/2 · Ja + 1/2 · Nein) / Gesamt

eher

    (1/2 · Ja + 1/2 · Nein + Enthaltung) / Gesamt

Weil wir in dem Bar immer Ja-Nein-Enthaltung haben..?

Valider Punkt denk ich. Danke fuer den Hinweis und die Idee!
Hab ich aber keine starke Meinung zu. Was denken die anderen? @tomthe ..?

**Comment by tomthe** [comment]
Joa, wäre ein bisschen schöner. Aber prioritätsmäßig eher nicht ganz so wichtig meiner Meinung nach.

**Comment by binfalse** [comment]
Ist live!

Danke @d-nnis fuers reporten! :)

**Comment by d-nnis** [comment]
Gerne gerne! :-)
